import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db/client';
import { getCurrentUser } from '@/lib/auth/index';
import slugify from '@/lib/utils/slugify';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { title, projectId, linkContextNotes, linkTask } = await request.json();

    if (!title?.trim()) {
      return NextResponse.json({ error: 'Title is required' }, { status: 400 });
    }

    // Get agent task with latest output
    const task = await db.execute({
      sql: `
        SELECT at.*, ato.content, ato.model_used, ato.created_at as output_created_at,
               ac.display_name as agent_name
        FROM agent_tasks at
        LEFT JOIN agent_task_outputs ato ON ato.agent_task_id = at.id
        LEFT JOIN agent_configs ac ON ac.agent_type = at.assigned_agent
        WHERE at.id = ? AND at.user_id = ?
        ORDER BY ato.version_number DESC
        LIMIT 1
      `,
      args: [id, user.id],
    });

    if (!task.rows.length) {
      return NextResponse.json({ error: 'Task not found' }, { status: 404 });
    }

    const taskData = task.rows[0] as any;

    if (!taskData.content) {
      return NextResponse.json({ error: 'No output to save' }, { status: 400 });
    }

    // Build note content with metadata footer
    const timestamp = new Date(taskData.output_created_at).toLocaleString();
    let noteContent = taskData.content;

    // Add metadata footer
    noteContent += '\n\n---\n\n';
    noteContent += `*Generated by ${taskData.agent_name} using ${taskData.model_used}*\n`;
    noteContent += `*Created: ${timestamp}*\n`;

    if (linkTask) {
      noteContent += `*Task: [${taskData.title}](/review?task=${id})*\n`;
    }

    if (linkContextNotes && taskData.context_note_ids) {
      const contextNoteIds = JSON.parse(taskData.context_note_ids);
      if (contextNoteIds.length > 0) {
        const contextNotes = await db.execute({
          sql: `SELECT id, title, slug FROM notes WHERE id IN (${contextNoteIds.map(() => '?').join(',')})`,
          args: contextNoteIds,
        });

        if (contextNotes.rows.length > 0) {
          noteContent += '\n**Context Notes:**\n';
          for (const note of contextNotes.rows as any[]) {
            noteContent += `- [${note.title}](/notes/${note.slug})\n`;
          }
        }
      }
    }

    // Create note
    const slug = slugify(title.trim());
    let finalSlug = slug;
    let counter = 1;

    // Ensure unique slug
    while (true) {
      const existing = await db.execute({
        sql: 'SELECT id FROM notes WHERE user_id = ? AND slug = ?',
        args: [user.id, finalSlug],
      });

      if (existing.rows.length === 0) break;
      finalSlug = `${slug}-${counter}`;
      counter++;
    }

    const noteId = crypto.randomUUID();
    await db.execute({
      sql: `
        INSERT INTO notes (id, user_id, project_id, title, slug, content, note_type)
        VALUES (?, ?, ?, ?, ?, ?, 'note')
      `,
      args: [noteId, user.id, projectId || null, title.trim(), finalSlug, noteContent],
    });

    return NextResponse.json({ noteId, slug: finalSlug });
  } catch (error) {
    console.error('Save to note error:', error);
    return NextResponse.json(
      { error: 'Failed to save note' },
      { status: 500 }
    );
  }
}
